
name: pizzapopan_pos
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/other/pizzapopan_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/backgrounds/
    - assets/images/boneless/
    - assets/images/drinks/
    - assets/images/extras/
    - assets/images/pizzas/
    - assets/menu.json
